name: CI

on:
  push:
    branches: [master, main, docs]
  pull_request:
    branches: [master, main]

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      
      - name: Install KIM-API (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y kim-api
          
      - name: Install KIM-API (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install kim-api
          
      - name: Install KIM-API (Windows)
        if: runner.os == 'Windows'
        run: |
          # Windows KIM-API installation would need to be set up
          # For now, skip KIM-API installation on Windows
          echo "KIM-API installation on Windows not yet supported"
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          
      - uses: julia-actions/cache@v1
      
      - uses: julia-actions/julia-buildpkg@v1
        
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: 2
        
      - uses: julia-actions/julia-processcoverage@v1
        
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false